version: "3"
services:
  php:
    image: php
    # container_name: myphp
    ##  这个选项可以自定义生成的镜像名称
    
    restart: always
    ## 容器自动重启
    
    depends_on:
      - mysql
      - nginx
    ## 控制容器启动顺序
    
    volumes:
      - "./config/php:/etc/php"
    networks:
      - dnmp


  nginx:
    image: nginx
    restart: always
    ports:
      - "8009:80"
    volumes:
      - "./www:/usr/share/nginx/html"
      - "./config/nginx:/etc/nginx/conf.d"
    networks:
      - dnmp


  mysql:
    image: mysql
    restart: always
    ports:
      - "8010:3306"
    environment:
            MYSQL_ROOT_PASSWORD: "yourpassword"
            MYSQL_USER: 'test'
            MYSQL_PASS: 'yourpassword'
    restart: always
        volumes:
            - "./conf/mysql:/etc/mysql"
            - "./data:/docker-entrypoint-initdb.d/"
            ##/docker-entrypoint-initdb.d/docker-entrypoint.sh 这个文件会自动执行 可以用于数据库初始化数据
        ports:
            - "3307:33060"
    networks:
      - dnmp


networks:
  dnmp: